[package]
name = "imoney-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
byteorder.workspace = true
blake3.workspace = true
thiserror.workspace = true
rand.workspace = true
bech32 = "0.12.0"
ed25519-dalek.workspace = true
